owner: andratwiro
repo: augur-uptime
sites:
  - name: Augur
    url: https://deltastudio.augur.page/_build.json
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
assignees: []
workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "0 23 * * *"
  graphs: "0 0 * * *"
  summary: "0 0 * * *"
  staticSite: "0 1 * * *"
  updateTemplate: "0 0 1 * *"
  updates: "0 3 * * *"
commitMessages:
  readmeContent: ":pencil: Update summary in README"
  summaryJob: ":card_file_box: Update summary"
  statusChange: "{{ emoji }} {{ site.name }} is {{ status }} ({{ site.url }})"
status-website:
  baseUrl: /augur-uptime
  name: Augur
  introTitle: "**Augur** uptime"
  introMessage: Uptime of Augur, checked every 5 minutes.
  logoUrl: ""
  navbar:
    - title: Status
      href: /
  metaTags:
    - name: robots
      content: noindex
  robotsText: |-
    User-agent: *
    Disallow: /
